# COSE474-2024: Deep Learning HW1

### 0.1 Installation

In [ ]:
!pip install d2l==1.0.3

# 2.1 Data Manipulation

In [2]:
import torch

In [3]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
#Number of elements
x.numel()

12

In [5]:
#length along each axis
x.shape

torch.Size([12])

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
#Tensor initialized to contain all 0s
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#tensor with 1s
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
#Random elements
torch.randn(3,4)

tensor([[ 0.9057, -0.1165,  0.2475,  1.5784],
        [-0.0614, -1.0715, -0.5966,  0.5404],
        [ 0.8881,  0.4112, -1.2945,  0.8778]])

In [10]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 Indexing and Slicing

In [11]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [12]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
#Applying the same value to multiple elements
X[:2, :] = 12 #Changes every element to 12 but the last row
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.3 Operations

In [14]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [15]:
x = torch.tensor([1.0, 2,4, 8])
y = torch.tensor([2,2,2,2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [16]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1) #dim -> the dimension over which the tensors are concatenated

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
X.sum()

tensor(66.)

### 2.1.4 Broadcasting

In [19]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [20]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.5 Saving Memory

In [21]:
#Running operations can cause new memory to be allocated to host results
before = id(Y)
Y = Y + X
id(Y) == before #Result of Y + X is allocated in new address, and then points Y to this new location in memory

False

In [22]:
#We want to perform updates in the same location
Z = torch.zeros_like(Y) # have same shape as Y
print('id(Z): ',id(Z))
Z[:] = X + Y # by using Z[:] = <expression> we can assign the result of an operation to an already allocated array Z
print('id(Z): ',id(Z))


id(Z):  138518764789152
id(Z):  138518764789152


In [23]:
before = id(X)
X += Y
id(X) == before

True

### 2.1.6 Conversion to Other Python Objects

In [24]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [25]:
#convert size-1 tensor to Python scalar => item function
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## Discussions & Exercises

- torch.randn(), creates a tensor with elements drawn from a standard Gaussian (normal) distribution with mean 0 and standard deviation 1
- Indexing starts with 0
- Negative indexing to access an element based on its position relative to the end of the list
- Ranges: X[start:stop], first element(start) included, last(stop) not included
- Only one index for a kth-order tensor is specified, it is applied along axis 0
- Elementwise operators => two tensors of the same shape
- Linear algebraic operations: dot products, matrix multiplications, ...
- Broadcasting:
  - Expand one or both arrays by copying elements along axes with length 1 => both tensors will have the same shape
  - Perform elementwise operation on the resulting arrays
- Tensor class is the main interface for storing and manipulating data in deep learning libraries



### Exercises



1.   Change the conditional statement X == Y to X < Y or X > Y, and then see what kind of tensor you can get.




In [26]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
X == Y, X < Y, X > Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

2. Replace the two tensors that operate by element in the broadcasting mechanism with other shapes, e.g., 3-dimensional tensors. Is the result the same as expected?

In [27]:
a = torch.arange(4).reshape((4,1))
b = torch.arange(5).reshape((1,5))
a, b

(tensor([[0],
         [1],
         [2],
         [3]]),
 tensor([[0, 1, 2, 3, 4]]))

In [28]:
a+b

tensor([[0, 1, 2, 3, 4],
        [1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6],
        [3, 4, 5, 6, 7]])

In [29]:
a-b

tensor([[ 0, -1, -2, -3, -4],
        [ 1,  0, -1, -2, -3],
        [ 2,  1,  0, -1, -2],
        [ 3,  2,  1,  0, -1]])

In [30]:
a*b

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  1,  2,  3,  4],
        [ 0,  2,  4,  6,  8],
        [ 0,  3,  6,  9, 12]])

In [31]:
a/b

tensor([[   nan, 0.0000, 0.0000, 0.0000, 0.0000],
        [   inf, 1.0000, 0.5000, 0.3333, 0.2500],
        [   inf, 2.0000, 1.0000, 0.6667, 0.5000],
        [   inf, 3.0000, 1.5000, 1.0000, 0.7500]])

In [32]:
a ** b

tensor([[ 1,  0,  0,  0,  0],
        [ 1,  1,  1,  1,  1],
        [ 1,  2,  4,  8, 16],
        [ 1,  3,  9, 27, 81]])