# 2.3 Linear Algebra

In [1]:
import torch

### 2.3.1 Scalars

In [2]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
x = torch.arange(3)
x

tensor([0, 1, 2])

In [4]:
x[2]

tensor(2)

In [5]:
len(x)

3

In [6]:
x.shape

torch.Size([3])

### 2.3.3 Matrices

In [7]:
A = torch.arange(6).reshape(3,2)
A

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [8]:
#Matrix's transpose
A.T

tensor([[0, 2, 4],
        [1, 3, 5]])

In [9]:
A = torch.tensor([[1,2,3], [2,0,4], [3,4,5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### 2.3.4 Tensors

In [10]:
torch.arange(24).reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 2.3.5 Basic Properties of Tensor Arithmetic

In [11]:
A = torch.arange(6,dtype=torch.float32).reshape(2,3)
B = A.clone()#Assign a copy of A to B by allocating new memory
A, A + B

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[ 0.,  2.,  4.],
         [ 6.,  8., 10.]]))

In [12]:
A * B # Hadamard product

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [13]:
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

### 2.3.6 Reduction

In [14]:
x = torch.arange(3,dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2.]), tensor(3.))

In [15]:
A.shape, A.sum()

(torch.Size([2, 3]), tensor(15.))

In [16]:
A.shape, A.sum(axis=0).shape

(torch.Size([2, 3]), torch.Size([3]))

In [17]:
A.shape, A.sum(axis=1).shape

(torch.Size([2, 3]), torch.Size([2]))

In [18]:
A.sum(axis=[0,1]) == A.sum()

tensor(True)

In [19]:
A.mean(), A.sum()/A.numel()

(tensor(2.5000), tensor(2.5000))

In [20]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([1.5000, 2.5000, 3.5000]), tensor([1.5000, 2.5000, 3.5000]))

### 2.3.7 Non-Reduction Sum

In [21]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A, sum_A.shape

(tensor([[ 3.],
         [12.]]),
 torch.Size([2, 1]))

In [22]:
A / sum_A

tensor([[0.0000, 0.3333, 0.6667],
        [0.2500, 0.3333, 0.4167]])

In [23]:
#Cumulative sum of elements along some axis
A.cumsum(axis=0)

tensor([[0., 1., 2.],
        [3., 5., 7.]])

### 2.3.8 Dot Products

In [24]:
y = torch.ones(3,dtype=torch.float32)
x,y, torch.dot(x,y)

(tensor([0., 1., 2.]), tensor([1., 1., 1.]), tensor(3.))

In [25]:
torch.sum(x*y)

tensor(3.)

### 2.3.9 Matrix-Vector Products

In [26]:
A.shape, x.shape, torch.mv(A,x), A@x

(torch.Size([2, 3]), torch.Size([3]), tensor([ 5., 14.]), tensor([ 5., 14.]))

### 2.3.10 Matrix-Matrix Multiplication

In [27]:
B = torch.ones(3,4)
torch.mm(A,B), A@B

(tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]),
 tensor([[ 3.,  3.,  3.,  3.],
         [12., 12., 12., 12.]]))

### 2.3.11 Norms

In [28]:
u = torch.tensor([3.0,-4.0])
torch.norm(u) #l2 norm

tensor(5.)

In [29]:
torch.abs(u).sum() #l1 norm

tensor(7.)

In [30]:
torch.norm(torch.ones((4,9)))

tensor(6.)

## Discussions & Exercises

2.3.3 Matrices
* transpose: exchange a matrix's rows and columns
* Symmetric matrices: subset of square matrices that are equal to their own transposes. For a matrix to be symmetric, the elements across the diagonal must mirror each other.
2.3.5 Basic Properties of Tensor Arithmetic
* The elementwise product of two matrices is called their Hadamard product
2.3.6 Reduction
* Sum of a tensor's elements $\sum_{i=1}^n x_{i}$
* By default, invoking the sum function reduces a tensor along all of its axes, eventually producing a scalar. Our libraries also allow us to specify the axes along which the tensor should be reduced. To sum over all elements along the rows (axis 0), we specify axis=0 in sum.
2.3.11 Norms
* The norm of a vector tells us how big it is.
* A norm is a function that maps a vector to a scalar.
* $\ell_{1}$ norm, its associated measure is called the Manhattan distance. Sums the absolute values of a vector's elements.
$$
\|\mathbf{x}\|_1 = \sum_{i=1}^{n} |x_i|
$$
* $\ell_{2}$ norm measures the (Euclidean) length of a vector. The square root of the sum of a squares of a vector's elements
$$
\|\mathbf{x}\|_2 = \sqrt{ \sum_{i=1}^{n} x_i^2 }
$$


### Exercises

1. Prove that the transpose of the transpose of a matrix is the matrix itself
$$(A^{\top})^{\top} = A$$

In [34]:
A = torch.arange(16,dtype=torch.float32).reshape(4,4)
torch.allclose(A, A.T.T) # checks if two tensors are approximately equal by allowing a small tolerance

True

2. Given two matrices A and B, show that sum and transposition commute:
$$  A^{\top} + B^{\top} = (A+B)^{\top}
$$

In [35]:
B = A.clone()
#A.T + B.T == (A+B).T
torch.allclose((A + B).T, A.T + B.T)

True

3. Given any square matrix A, is A + $A^{\top}$  always symmetric?

To prove that A + $A^{\top}$, then:
$$ A + A^{\top} = (A + A^{\top})^{\top}
$$

In [37]:
torch.allclose(A + A.T, (A + A.T).T)

True

4. We defined the tensor X of shape (2, 3, 4) in this section. What is the output of len(X)? Write your answer without implementing any code, then check your answer using code.

len(X) would be 2, that's its first dimension

In [38]:
X = torch.arange(24).reshape(2,3,4)

In [42]:
len(X) #For a tensor A of shape (x,n,z), its demensionality or len(A) is x

2

5. For a tensor X of arbitrary shape, does len(X) always correspond to the length of a certain axis of X? What is that axis?

Yes, len(X) corresponds to the length of the axis 0

6. Run A / A.sum(axis=1) and see what happens. Can you analyze the results?

In [47]:
A, A.sum(axis=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 tensor([ 6., 22., 38., 54.]))

In [45]:
A / A.sum(axis=1)

tensor([[0.0000, 0.0455, 0.0526, 0.0556],
        [0.6667, 0.2273, 0.1579, 0.1296],
        [1.3333, 0.4091, 0.2632, 0.2037],
        [2.0000, 0.5909, 0.3684, 0.2778]])

A / A.sum(axis=1) divides each element of A by the sum of the elements in the row that element is in.

7. Consider a tensor of shape (2, 3, 4). What are the shapes of the summation outputs along axes 0, 1, and 2?

In [48]:
X = torch.arange(24).reshape(2,3,4)

In [50]:
X.sum(axis=0).shape, X.sum(axis=1).shape, X.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))